#!/bin/bash

# Vim/Nvim
# ========

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  /usr/bin/vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping Nvim"
  nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
